# Generated by Django 5.0 on 2024-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coursecategory_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
