# Generated by Django 5.0 on 2024-11-10 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_is_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
