# Generated by Django 5.0 on 2024-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_course_credits_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image_url',
            new_name='image_url_1',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_url_2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_url_3',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_url_4',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_url_5',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_url_6',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_name',
            field=models.CharField(blank=True, default='Gallery', max_length=255, null=True),
        ),
    ]
