# Generated by Django 5.0 on 2024-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_academicdepartment_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementdepartment',
            name='department_type',
            field=models.CharField(default='management', max_length=50),
        ),
    ]
